/*
 * This source file was generated by the Gradle 'init' task
 */
package ru.fourcode.BeansGviz;

import com.google.gson.Gson;
import java.io.File;
import java.io.IOException;
import java.io.PrintStream;


public class App {
    
    public static void main(String[] args) throws Exception{
        
        if(args.length < 1){
            System.err.println("usage: BeansGviz <url/to/actuator/beans> "
                    +"[path/to/out/dir/or/file]");
            System.exit(1);
        }
        
        String url = args[0];
        String outPath = args.length > 1 ? args[1] : null;
        
        var bns = new Gson().fromJson(
            Util.httpGet(url),
            ActuatorBeans.class
        );
        
        var printStreamProvider = outPath == null 
                ? new StdoutPrintStreamProvider()
                : new FilePrintStreamProvider(new File(outPath));
        
        bns.printGraphviz(printStreamProvider);
    }
    
}
